#!/bin/bash


# This script checks if a file exists in the current directory

file_name="example.txt"

if [ -e "$file_name" ]; then
    echo "File $file_name exists."
else
    echo "File $file_name does not exist."
fi

